name: Create Container App silo

on:
  push:
    branches:
    - main

env:
  
  # alphanumeric string under 14 characters
  RESOURCE_GROUP_NAME: smarthome

  # specify your preferred region
  REGION: "'West Europe'"

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create resource group
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Creating resource group in Azure"
          #!/bin/bash
          if $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) ; then
            echo "Azure resource group already exists, skipping creation..."
          else
            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.REGION }}
            echo "Azure resource group created"
          fi 
          #echo "Executing 'az group create -l ${{ env.REGION }} -n ${{ env.RESOURCE_GROUP_NAME }}'"
          #az group create -l ${{ env.REGION }} -n ${{ env.RESOURCE_GROUP_NAME }}
    - name: Creating resources
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Creating resources"
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --template-file '/github/workspace/deploy/azure/main.bicep' \
            --parameters registryName='docker.io' registryUserName='${{ secrets.DOCKER_HUB_USERNAME }}' registryPassword='${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'\
            --debug
